config/routes.rb
Urbanfactory::Application.routes.draw do

  get 'aboutus' => 'pages#about'
	root 'pages#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.haml
-#Footer Area
.footer-container
  .container
    .row.footer-row
      .span3.footer-col
        %h5 Contact Us
        = image_tag 'wonder-footer-logo.png', alt: "Wonder"
        %br
        %br
        %address
          %strong Wonder Bunker
          %br
          "6064 Amazing St,"
          %br
          "Madrid, Spain"
          %br
        %ul.social-icons
          %li= link_to "", "#", class: "social-icon facebook"
          %li= link_to "", "#", class: "social-icon twitter"
          %li= link_to "", "#", class: "social-icon instagram"
      .span3.footer-col
        %h5 Latest Tweets
        %ul
          %li= link_to "@Basicoh_", "#"
          "Hey! Buy this beautiful theme right now!"
          %li= link_to "@Basicoh_", "#"
          "Wonder Theme is out Now! You can buy it in Wrapbootstrap.com. Really easy to configure with a wonderful design."
          %li= link_to "@Basicoh_", "#"
          "If you are an agency, freelancer or a studio, this theme is made for you. Take a look and enjoy it."
      .span3.footer-col
        %h5 Latest Posts
        %ul.post-list
          %li= link_to "Example post number 1", "#"
          %li= link_to "Another example post title", "#"
          %li= link_to "This is the third post title here", "#"
          %li= link_to "Yet another post title for this list", "#"
          %li= link_to "No more posts, this is the last one", "#"
      .span3.footer-col
        %h5 Flicker Photos
        %ul.img-feed
          %li= link_to image_tag('gallery/flickr-img-1.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-2.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-3.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-4.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-5.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-6.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-7.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-8.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-9.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-10.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-11.jpg', alt: "Image Feed"), "#"
          %li= link_to image_tag('gallery/flickr-img-12.jpg', alt: "Image Feed"), "#"

    .row
      .span12.footer-col.footer-sub
        .row.no-margin
          .span6
            %span.left &copy; 2014 UrbanFactory8
          .span6
            %span.right
              = link_to "Home", root_path
              &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
              = link_to 'About Us', aboutus_path
              &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
              = link_to 'Portfolio', "#"
              &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
              = link_to 'Contact', "#"
              &nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
#toTop.hidden-phone.hiddent-tablet Back to Top

app/views/layouts/_header.html.haml
-#Begin Header
.row.header.no-margin
  .span5.logo
    = link_to image_tag('1uf8_logo.png', class: 'logo'), root_path

  .span7.navigation
    .navbar.hidden_phone
      %ul.nav
        %li.active
          = link_to 'Home', root_path
        %li= link_to 'About Us', aboutus_path
        %li= link_to 'Portfolio', "#"
        %li= link_to 'Contact', "#"
-#End Header

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "UrbanFactory"
    %meta{content: content_for?(:description) ? yield(:description) : "Awesome Branding", name: "description"}/
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %link{href: "http://fonts.googleapis.com/css?family=Arvo", rel: "stylesheet", type: "text/css"}
    /[if lt IE 9]
      %script{href: "http://html5shim.googlecode.com/svn/trunk/html5.js"}
      =stylesheet_link_tag "style-ie.css", media: "all"

    = yield :head

  %body
    .color-bar-1
    .color-bar-2.color-bg
    .container
      = render 'layouts/header'
      -#= render 'layouts/messages'
      = yield
    = render 'layouts/footer'

app/views/pages/about.html.haml
.row
  .span8
    / Begin page content column
    %h2 Right Sidebar
    %p.lead Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
    %h5.title-bg Recent Works
    .row
      .span2
        =image_tag "gallery/gallery-img-1-4col.jpg", class: "thumbnail", alt: "Image"
        %h5 Project 1
        %p Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.
      .span2
        =image_tag "gallery/gallery-img-2-4col.jpg", class: "thumbnail", alt: "Image"
        %h5 Project 2
        %p Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.
      .span2
        =image_tag "gallery/gallery-img-3-4col.jpg", class: "thumbnail", alt: "Image"
        %h5 Project 3
        %p Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.
      .span2
        =image_tag "gallery/gallery-img-4-4col.jpg", class: "thumbnail", alt: "Image"
        %h5 Project 4
        %p Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC, making it over 2000 years old.
    %h5.title-bg Important Work
    .clearfix
      =image_tag "gallery/gallery-img-5-4col.jpg", class: "thumbnail align-left", alt: "Image"
      %p Vivamus augue nulla, vestibulum ac ultrices posuere, vehicula ac arcu. Quisque nisi lacus, bibendum quis commodo eget, lobortis eget elit. Cras venenatis mauris eu tortor consequat a convallis nulla molestie. Phasellus malesuada malesuada velit et fermentum. Proin ut leo nec mauris pulvinar volutpat. Sed ac neque nec leo condimentum rhoncus.
      %p Quisque nisi lacus, bibendum quis commodo eget, lobortis eget elit. Cras venenatis mauris eu tortor consequat a convallis nulla molestie.
      %button.btn.btn-small.btn-inverse{type: "button"} Visit Website
  / End page content column
  /
    Blog Sidebar
    \==================================================
  .span4.sidebar.page-sidebar
    / Begin sidebar column
    / Tabbed Content
    %h6.title-bg More Info
    %ul.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", href: "#comments"} Comments
      %li
        %a{"data-toggle" => "tab", href: "#tweets"} Tweets
      %li
        %a{"data-toggle" => "tab", href: "#about"} About
    .tab-content
      #comments.tab-pane.active
        %ul
          %li
            %i.icon-comment>
            admin on
            %a{href: "#"} Project 1
          %li
            %i.icon-comment>
            admin on
            %a{href: "#"} Project 2
          %li
            %i.icon-comment>
            admin on
            %a{href: "#"} Project 3
      #tweets.tab-pane
        %ul
          %li
            %a{href: "#"}
              %i.icon-comment>
              @Basicoh_
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
          %li
            %a{href: "#"}
              %i.icon-comment>
              @Basicoh_
            In interdum felis fermentum ipsum molestie sed porttitor ligula rutrum. Morbi blandit ultricies ultrices.
          %li
            %a{href: "#"}
              %i.icon-comment>
              @Basicoh_
            Vivamus nec lectus sed orci molestie molestie.
      #about.tab-pane
        %p Lorem ipsum dolor sit amet, consectetur adipiscing elit. In interdum felis fermentum ipsum molestie sed porttitor ligula rutrum. Morbi blandit ultricies ultrices. Vivamus nec lectus sed orci molestie molestie.
    / Testimonials
    %h6.title-bg Testimonials
    %p.quote-text.side
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In interdum felis fermentum ipsum molestie sed porttitor ligula rutrum. Morbi blandit ultricies ultrices. Vivamus nec lectus sed orci molestie molestie."
      %cite - First Client, Company Name
    %p.quote-text.side
      "Adipiscing elit. In interdum felis fermentum ipsum molestie sed porttitor ligula rutrum. Morbi blandit ultricies ultrices. Vivamus nec lectus sed orci molestie molestie."
      %cite - Second Client, Company Name
    / Latest News
    %h6.title-bg Latest Posts
    %ul.popular-posts
      %li
        %a{href: "#"}
          =image_tag "gallery/gallery-img-6-thumb.jpg", alt: "Popular Post"
        %h6
          %a{href: "#"} Lorem ipsum dolor sit amet consectetur adipiscing elit
        %em Posted on 02/21/13
      %li
        %a{href: "#"}
          =image_tag "gallery/gallery-img-7-thumb.jpg", alt: "Popular Post"
        %h6
          %a{href: "#"} Lorem ipsum dolor sit amet consectetur adipiscing elit
        %em Posted on 03/01/13
      %li
        %a{href: "#"}
          =image_tag "gallery/gallery-img-8-thumb.jpg", alt: "Popular Post"
        %h6
          %a{href: "#"} Lorem ipsum dolor sit amet consectetur adipiscing elit
        %em Posted on 05/16/13

app/views/pages/index.html.haml
.row.headline
  / Begin Headline
  /
    Slider Carousel
    \==================================================
  .span8
    .flexslider
      %ul.slides
        %li= link_to image_tag('gallery/slider1.jpg'), "#"
        %li= link_to image_tag('gallery/slider2.jpg'), "#", alt: 'slider'
        %li= link_to image_tag('gallery/slider3.jpg'), "#", alt: 'slider'
  /
    Headline Text
    \==================================================
  .span4
    %h3
      This is Wonderful.
      %br/
      Wonder is a beautiful multipurpose HTML/CSS Theme.
    %p.lead 18+ html pages crafted with love! Responsive Design. BUY ME!
/ End Headline
.row.gallery-row
  / Begin Gallery Row
  .span12
    %h5.title-bg
      Take a Look
      %small at our recent work
      %button.btn.btn-mini.hidden-phone{type: "button"} View Portfolio
    /
      Gallery Thumbnails
      \==================================================
    .row.clearfix.no-margin
      %ul.gallery-post-grid.holder
        / Gallery Item 1
        %li.span3.gallery-item{"data-id" => "id-1", "data-type" => "illustration"}
          %span.gallery-hover-4col.hidden-phone.hidden-tablet
            %span.gallery-icons
              %a.item-zoom-link.lightbox{"data-rel" => "prettyPhoto", href: "img/gallery/gallery-img-full.jpg", title: "Custom Illustration"}
              %a.item-details-link{href: "gallery-single.htm"}
          = link_to image_tag('gallery/gallery-img-1-4col.jpg', alt: 'Gallery'), '#'
          %span.project-details
            %a{href: "gallery-single.htm"}> Bad Dinosaur
            Not so bad really.
        / Gallery Item 2
        %li.span3.gallery-item{"data-id" => "id-2", "data-type" => "illustration"}
          %span.gallery-hover-4col.hidden-phone.hidden-tablet
            %span.gallery-icons
              %a.item-zoom-link.lightbox{"data-rel" => "prettyPhoto", href: "img/gallery/gallery-img-full.jpg", title: "Custom Illustration"}
              %a.item-details-link{href: "gallery-single.htm"}
          = link_to image_tag('gallery/gallery-img-2-4col.jpg', alt: 'Gallery'), '#'
          %span.project-details
            %a{href: "gallery-single.htm"}> I come in peace
            Take me with your leader.
        / Gallery Item 3
        %li.span3.gallery-item{"data-id" => "id-3", "data-type" => "web"}
          %span.gallery-hover-4col.hidden-phone.hidden-tablet
            %span.gallery-icons
              %a.item-zoom-link.lightbox{"data-rel" => "prettyPhoto", href: "img/gallery/gallery-img-full.jpg", title: "Custom Illustration"}
              %a.item-details-link{href: "#"}
          = link_to image_tag('gallery/gallery-img-3-4col.jpg', alt: 'Gallery'), '#'
          %span.project-details
            %a{href: "gallery-single.htm"}> Pink Unicorn
            Yes, Unicorns are Pink.
        / Gallery Item 4
        %li.span3.gallery-item{"data-id" => "id-4", "data-type" => "video"}
          %span.gallery-hover-4col.hidden-phone.hidden-tablet
            %span.gallery-icons
              %a.item-zoom-link.lightbox{"data-rel" => "prettyPhoto", href: "img/gallery/gallery-img-full.jpg", title: "Custom Illustration"}
              %a.item-details-link{href: "gallery-single.htm"}
          = link_to image_tag('gallery/gallery-img-4-4col.jpg', alt: 'Gallery'), '#'
          %span.project-details
            %a{href: "gallery-single.htm"}> Really Bad Guy
            Also I love skates.
/ End Gallery Row
.row
  / Begin Bottom Section
  /
    Blog Preview
    \==================================================
  .span6
    %h5.title-bg
      Check it out
      %small Latest featured
      %button.btn.btn-inverse.btn-mini#btn-blog-next{type: "button"} »
      %button#btn-blog-prev.btn.btn-inverse.btn-mini{type: "button"} «
    #blogCarousel.carousel.slide
      / Carousel items
      .carousel-inner
        / Blog Item 1
        .active.item
          = link_to image_tag('gallery/blog-med-img-1.jpg', alt: '', class: 'align-left blog-thumb-preview'), '#'
          .post-info.clearfix
            %h4
              %a{href: "blog-single.htm"} You are Super Awesome.
            %ul.blog-details-preview
              %li
                %i.icon-calendar
                %strong Posted on:
                Aug 14, 2013
              %li
              %li
                %i.icon-user
                %strong Posted by:
                %a{href: "#", title: "Link"} Admin
              %li
              %li
                %i.icon-comment
                %strong Comments:
                %a{href: "#", title: "Link"} 8
              %li
              %li
                %i.icon-tags
                = succeed "," do
                  %a{href: "#"} artwork
                = succeed "," do
                  %a{href: "#"} craft
          %p.blog-summary
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In interdum felis fermentum
            ipsum molestie sed porttitor ligula rutrum.
            %a{href: "#"} Read more
          %p
        / Blog Item 2
        .item
          = link_to image_tag('gallery/blog-med-img-2.jpg', alt: '', class: 'align-left blog-thumb-preview'), '#'
          .post-info.clearfix
            %h4
              %a{href: "blog-single.htm"} Han Shot First!
            %ul.blog-details-preview
              %li
                %i.icon-calendar
                %strong Posted on:
                May 7, 2013
              %li
              %li
                %i.icon-user
                %strong Posted by:
                %a{href: "#", title: "Link"} Admin
              %li
              %li
                %i.icon-comment
                %strong Comments:
                %a{href: "#", title: "Link"} 6
              %li
              %li
                %i.icon-tags
                = succeed "," do
                  %a{href: "#"} artwork
                %a{href: "#"} draw
          %p.blog-summary
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. In interdum felis fermentum
            ipsum molestie sed porttitor ligula rutrum.
            %a{href: "#"} Read more
          %p
  /
    Video Area
    \==================================================
  .span6
    %h5.title-bg
      UrbanFactory8
      %small check out our video
    %iframe{allowfullscreen: "", frameborder: "0", height: "300", mozallowfullscreen: "", src: "http://player.vimeo.com/video/44049449", webkitallowfullscreen: "", width: "100%"}
/ End Bottom Section
/ End Container